version: '3.8'

services:
  jenkins-master:
    image: jenkins/jenkins:lts
    container_name: jenkins-master
    mem_limit: 5g
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
      - "5005:5005"
    volumes:
      - ./jenkins_data:/var/jenkins_home
      - ./target/pipeline-agent-build-history.hpi:/var/jenkins_home/plugins/pipeline-agent-build-history.hpi
      - /mnt/c/CA/Vector_Root_CA_2.0.crt:/usr/local/share/ca-certificates/Vector_Root_CA_2.0.crt:ro
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -Dhudson.security.csrf.GlobalCrumbIssuerConfiguration.DISABLE_CSRF_PROTECTION=true
      - JENKINS_OPTS=-Dhudson.security.csrf.GlobalCrumbIssuerConfiguration.DISABLE_CSRF_PROTECTION=true
    entrypoint: >
      /bin/bash -c "
      update-ca-certificates &&
      keytool -delete -alias vector-ca -cacerts -storepass changeit || true &&
      keytool -importcert -noprompt -trustcacerts -alias vector-ca -file /usr/local/share/ca-certificates/Vector_Root_CA_2.0.crt -cacerts -storepass changeit &&
      /usr/bin/tini -- /usr/local/bin/jenkins.sh
      "
    networks:
      - jenkins

  jenkins-agent-1:
    image: jenkins/inbound-agent
    container_name: jenkins-agent-1
    depends_on: [jenkins-master]
    mem_limit: 5g
    environment:
      - JENKINS_URL=http://jenkins-master:8080/
      - JENKINS_SECRET=0245f5232bed7086d932a8142004a748f6f3719ac84c83f15f4dc245a9471002
      - JENKINS_AGENT_NAME=agent-1
    networks:
      - jenkins

  jenkins-agent-2:
    image: jenkins/inbound-agent
    container_name: jenkins-agent-2
    depends_on: [jenkins-master]
    mem_limit: 5g
    environment:
      - JENKINS_URL=http://jenkins-master:8080/
      - JENKINS_SECRET=d6a23da8d25653977fc2ee5f38cf3ba02f475b3f122f845c61316168c713d5db
      - JENKINS_AGENT_NAME=agent-2
    networks:
      - jenkins

networks:
  jenkins:
    driver: bridge

volumes:
  jenkins_home:
